### ISSUE TITLE
Cannot read property 'slice' of undefined thrown if css or js file of the page cannot be downloaded

### ISSUE THREAD

**Issue by simonepri** [mirkoschubert/gdpr-check#2] opened 2018-05-28 17:17 UTC
## I'm submitting a

- [x] bug report

## Information

![image](https://user-images.githubusercontent.com/3505087/40624218-87319bc2-62ab-11e8-97d0-462f210cc2a5.png)

**Comment by mirkoschubert** [comment] 2018-05-28 19:38
@simonepri Can you please send me a URL, where this bug happened? I think, I know where the problem is, but I need an example.

**Comment by simonepri** [comment] 2018-05-28 20:11
If you add me on Twitter I'll DM it to you.

**Comment by mirkoschubert** [comment] 2018-05-29 05:54
@simonepri Done. ;)

**Comment by mirkoschubert** [comment] 2018-05-29 06:37
@simonepri Well, there is a problem with importing the main CSS and JS files, since they are imported relatively in the HTML file. So in other languages (like the Italian version) my script »thinks« these files would have the same language slug like the HTML file and gets an 404 error when loading them.
I didn't figure out just yet, how the website itself manages to render correctly in the browser. Try using this site without the Italian slug for now. In this case everything is fine. ;)

**Comment by simonepri** [comment] 2018-05-29 08:43
> "I didn't figure out just yet, how the website itself manages to render correctly in the browser"

That's how it works:
1) You ask for https://example.com/something
2) The web server answers you with the page https://example.com/index.html
3) /something is handled by some javascript using History APIs
4) You are only virtually at https://example.com/something so relative paths get resolved as if the page was https://example.com/index.html

> "gets an 404 error when loading them."

In order to avoid the exception thrown by slice, you can just check if the css is a valid string before slicing it.

> "Try using this site without the Italian slug for now."

A workaround to ""solve"" the problem with the relative path, may be the following:
1) You ask for https://example.com/something/else/
2) The page contains `<link rel="stylesheet" href="some-stylesheet.css">`
3) You ask for https://example.com/something/else/some-stylesheet.css first
4) If the request fails you can try https://example.com/something/some-stylesheet.css
5) If the request fails you can try https://example.com/some-stylesheet.css
6) If the request fails you have reached the root and there's nothing else you can do to guess the correct relative location. (Probably because the file does not really exists)
Practically, you try to locate the css in each directory in the pat from leaf to root.)

**Comment by mirkoschubert** [comment] 2018-05-29 12:12
@simonepri Thanks for the advice! I should have known that 😏 I fixed it already and will publish it in the next update.

**Comment by mirkoschubert** [comment] 2018-06-01 13:00
The version [0.3.3](https://github.com/mirkoschubert/gdpr-cli/releases/tag/v0.3.3) is now online, so I close this issue now.

**Closed as completed** 2018-06-01 13:00 UTC
Labels: bug
